[package]
name = "webserver"
version = "0.1.0"
authors = ["Kristin Barkardottir <kristin.barkardottir@netapp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
